// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// CheckListItem is an object representing the database table.
type CheckListItem struct {
	ItemID      string      `boil:"ItemID" json:"ItemID" toml:"ItemID" yaml:"ItemID"`
	Description null.String `boil:"Description" json:"Description,omitempty" toml:"Description" yaml:"Description,omitempty"`

	R *checkListItemR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L checkListItemL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var CheckListItemColumns = struct {
	ItemID      string
	Description string
}{
	ItemID:      "ItemID",
	Description: "Description",
}

var CheckListItemTableColumns = struct {
	ItemID      string
	Description string
}{
	ItemID:      "CheckListItems.ItemID",
	Description: "CheckListItems.Description",
}

// Generated where

var CheckListItemWhere = struct {
	ItemID      whereHelperstring
	Description whereHelpernull_String
}{
	ItemID:      whereHelperstring{field: "[dbo].[CheckListItems].[ItemID]"},
	Description: whereHelpernull_String{field: "[dbo].[CheckListItems].[Description]"},
}

// CheckListItemRels is where relationship names are stored.
var CheckListItemRels = struct {
}{}

// checkListItemR is where relationships are stored.
type checkListItemR struct {
}

// NewStruct creates a new relationship struct
func (*checkListItemR) NewStruct() *checkListItemR {
	return &checkListItemR{}
}

// checkListItemL is where Load methods for each relationship are stored.
type checkListItemL struct{}

var (
	checkListItemAllColumns            = []string{"ItemID", "Description"}
	checkListItemColumnsWithAuto       = []string{}
	checkListItemColumnsWithoutDefault = []string{"ItemID", "Description"}
	checkListItemColumnsWithDefault    = []string{}
	checkListItemPrimaryKeyColumns     = []string{"ItemID"}
)

type (
	// CheckListItemSlice is an alias for a slice of pointers to CheckListItem.
	// This should almost always be used instead of []CheckListItem.
	CheckListItemSlice []*CheckListItem
	// CheckListItemHook is the signature for custom CheckListItem hook methods
	CheckListItemHook func(context.Context, boil.ContextExecutor, *CheckListItem) error

	checkListItemQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	checkListItemType                 = reflect.TypeOf(&CheckListItem{})
	checkListItemMapping              = queries.MakeStructMapping(checkListItemType)
	checkListItemPrimaryKeyMapping, _ = queries.BindMapping(checkListItemType, checkListItemMapping, checkListItemPrimaryKeyColumns)
	checkListItemInsertCacheMut       sync.RWMutex
	checkListItemInsertCache          = make(map[string]insertCache)
	checkListItemUpdateCacheMut       sync.RWMutex
	checkListItemUpdateCache          = make(map[string]updateCache)
	checkListItemUpsertCacheMut       sync.RWMutex
	checkListItemUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var checkListItemBeforeInsertHooks []CheckListItemHook
var checkListItemBeforeUpdateHooks []CheckListItemHook
var checkListItemBeforeDeleteHooks []CheckListItemHook
var checkListItemBeforeUpsertHooks []CheckListItemHook

var checkListItemAfterInsertHooks []CheckListItemHook
var checkListItemAfterSelectHooks []CheckListItemHook
var checkListItemAfterUpdateHooks []CheckListItemHook
var checkListItemAfterDeleteHooks []CheckListItemHook
var checkListItemAfterUpsertHooks []CheckListItemHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *CheckListItem) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range checkListItemBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *CheckListItem) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range checkListItemBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *CheckListItem) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range checkListItemBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *CheckListItem) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range checkListItemBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *CheckListItem) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range checkListItemAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *CheckListItem) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range checkListItemAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *CheckListItem) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range checkListItemAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *CheckListItem) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range checkListItemAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *CheckListItem) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range checkListItemAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddCheckListItemHook registers your hook function for all future operations.
func AddCheckListItemHook(hookPoint boil.HookPoint, checkListItemHook CheckListItemHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		checkListItemBeforeInsertHooks = append(checkListItemBeforeInsertHooks, checkListItemHook)
	case boil.BeforeUpdateHook:
		checkListItemBeforeUpdateHooks = append(checkListItemBeforeUpdateHooks, checkListItemHook)
	case boil.BeforeDeleteHook:
		checkListItemBeforeDeleteHooks = append(checkListItemBeforeDeleteHooks, checkListItemHook)
	case boil.BeforeUpsertHook:
		checkListItemBeforeUpsertHooks = append(checkListItemBeforeUpsertHooks, checkListItemHook)
	case boil.AfterInsertHook:
		checkListItemAfterInsertHooks = append(checkListItemAfterInsertHooks, checkListItemHook)
	case boil.AfterSelectHook:
		checkListItemAfterSelectHooks = append(checkListItemAfterSelectHooks, checkListItemHook)
	case boil.AfterUpdateHook:
		checkListItemAfterUpdateHooks = append(checkListItemAfterUpdateHooks, checkListItemHook)
	case boil.AfterDeleteHook:
		checkListItemAfterDeleteHooks = append(checkListItemAfterDeleteHooks, checkListItemHook)
	case boil.AfterUpsertHook:
		checkListItemAfterUpsertHooks = append(checkListItemAfterUpsertHooks, checkListItemHook)
	}
}

// One returns a single checkListItem record from the query.
func (q checkListItemQuery) One(ctx context.Context, exec boil.ContextExecutor) (*CheckListItem, error) {
	o := &CheckListItem{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for CheckListItems")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all CheckListItem records from the query.
func (q checkListItemQuery) All(ctx context.Context, exec boil.ContextExecutor) (CheckListItemSlice, error) {
	var o []*CheckListItem

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to CheckListItem slice")
	}

	if len(checkListItemAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all CheckListItem records in the query.
func (q checkListItemQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count CheckListItems rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q checkListItemQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if CheckListItems exists")
	}

	return count > 0, nil
}

// CheckListItems retrieves all the records using an executor.
func CheckListItems(mods ...qm.QueryMod) checkListItemQuery {
	mods = append(mods, qm.From("[dbo].[CheckListItems]"))
	return checkListItemQuery{NewQuery(mods...)}
}

// FindCheckListItem retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindCheckListItem(ctx context.Context, exec boil.ContextExecutor, itemID string, selectCols ...string) (*CheckListItem, error) {
	checkListItemObj := &CheckListItem{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from [dbo].[CheckListItems] where [ItemID]=$1", sel,
	)

	q := queries.Raw(query, itemID)

	err := q.Bind(ctx, exec, checkListItemObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from CheckListItems")
	}

	if err = checkListItemObj.doAfterSelectHooks(ctx, exec); err != nil {
		return checkListItemObj, err
	}

	return checkListItemObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *CheckListItem) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no CheckListItems provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(checkListItemColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	checkListItemInsertCacheMut.RLock()
	cache, cached := checkListItemInsertCache[key]
	checkListItemInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			checkListItemAllColumns,
			checkListItemColumnsWithDefault,
			checkListItemColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(checkListItemType, checkListItemMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(checkListItemType, checkListItemMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO [dbo].[CheckListItems] ([%s]) %%sVALUES (%s)%%s", strings.Join(wl, "],["), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO [dbo].[CheckListItems] %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryOutput = fmt.Sprintf("OUTPUT INSERTED.[%s] ", strings.Join(returnColumns, "],INSERTED.["))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into CheckListItems")
	}

	if !cached {
		checkListItemInsertCacheMut.Lock()
		checkListItemInsertCache[key] = cache
		checkListItemInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the CheckListItem.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *CheckListItem) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	checkListItemUpdateCacheMut.RLock()
	cache, cached := checkListItemUpdateCache[key]
	checkListItemUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			checkListItemAllColumns,
			checkListItemPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, checkListItemColumnsWithAuto)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update CheckListItems, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE [dbo].[CheckListItems] SET %s WHERE %s",
			strmangle.SetParamNames("[", "]", 1, wl),
			strmangle.WhereClause("[", "]", len(wl)+1, checkListItemPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(checkListItemType, checkListItemMapping, append(wl, checkListItemPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update CheckListItems row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for CheckListItems")
	}

	if !cached {
		checkListItemUpdateCacheMut.Lock()
		checkListItemUpdateCache[key] = cache
		checkListItemUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q checkListItemQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for CheckListItems")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for CheckListItems")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o CheckListItemSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), checkListItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE [dbo].[CheckListItems] SET %s WHERE %s",
		strmangle.SetParamNames("[", "]", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, checkListItemPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in checkListItem slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all checkListItem")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *CheckListItem) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no CheckListItems provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(checkListItemColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	checkListItemUpsertCacheMut.RLock()
	cache, cached := checkListItemUpsertCache[key]
	checkListItemUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			checkListItemAllColumns,
			checkListItemColumnsWithDefault,
			checkListItemColumnsWithoutDefault,
			nzDefaults,
		)
		insert = strmangle.SetComplement(insert, checkListItemColumnsWithAuto)
		for i, v := range insert {
			if strmangle.ContainsAny(checkListItemPrimaryKeyColumns, v) && strmangle.ContainsAny(checkListItemColumnsWithDefault, v) {
				insert = append(insert[:i], insert[i+1:]...)
			}
		}
		if len(insert) == 0 {
			return errors.New("models: unable to upsert CheckListItems, could not build insert column list")
		}

		ret = strmangle.SetMerge(ret, checkListItemColumnsWithAuto)
		ret = strmangle.SetMerge(ret, checkListItemColumnsWithDefault)

		update := updateColumns.UpdateColumnSet(
			checkListItemAllColumns,
			checkListItemPrimaryKeyColumns,
		)
		update = strmangle.SetComplement(update, checkListItemColumnsWithAuto)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert CheckListItems, could not build update column list")
		}

		cache.query = buildUpsertQueryMSSQL(dialect, "[dbo].[CheckListItems]", checkListItemPrimaryKeyColumns, update, insert, ret)

		whitelist := make([]string, len(checkListItemPrimaryKeyColumns))
		copy(whitelist, checkListItemPrimaryKeyColumns)
		whitelist = append(whitelist, update...)
		whitelist = append(whitelist, insert...)

		cache.valueMapping, err = queries.BindMapping(checkListItemType, checkListItemMapping, whitelist)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(checkListItemType, checkListItemMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // MSSQL doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert CheckListItems")
	}

	if !cached {
		checkListItemUpsertCacheMut.Lock()
		checkListItemUpsertCache[key] = cache
		checkListItemUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single CheckListItem record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *CheckListItem) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no CheckListItem provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), checkListItemPrimaryKeyMapping)
	sql := "DELETE FROM [dbo].[CheckListItems] WHERE [ItemID]=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from CheckListItems")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for CheckListItems")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q checkListItemQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no checkListItemQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from CheckListItems")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for CheckListItems")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o CheckListItemSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(checkListItemBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), checkListItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM [dbo].[CheckListItems] WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, checkListItemPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from checkListItem slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for CheckListItems")
	}

	if len(checkListItemAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *CheckListItem) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindCheckListItem(ctx, exec, o.ItemID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *CheckListItemSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := CheckListItemSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), checkListItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT [dbo].[CheckListItems].* FROM [dbo].[CheckListItems] WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, checkListItemPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in CheckListItemSlice")
	}

	*o = slice

	return nil
}

// CheckListItemExists checks if the CheckListItem row exists.
func CheckListItemExists(ctx context.Context, exec boil.ContextExecutor, itemID string) (bool, error) {
	var exists bool
	sql := "select case when exists(select top(1) 1 from [dbo].[CheckListItems] where [ItemID]=$1) then 1 else 0 end"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, itemID)
	}
	row := exec.QueryRowContext(ctx, sql, itemID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if CheckListItems exists")
	}

	return exists, nil
}
